<?php

namespace Database\Seeders;

use App\Models\MenuItem;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuItemSeeder extends Seeder
{
    use WithoutModelEvents;

    private const TABLE = 'menu_items';

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::transaction(function (): void {
            $this->limpiarTabla();
            $menu_caja = [
                [
                    'id' => 1,
                    'title' => 'Inicio',
                    'default_url' => 'cajas/principal/index',
                    'icon' => 'fas fa-home',
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => null,
                    'codapl' => 'CA',
                    'controller' => 'PrincipalController',
                    'action' => 'index',
                ],
                [
                    'id' => 2,
                    'title' => 'Estadística',
                    'default_url' => 'cajas/principal/dashboard',
                    'icon' => 'ni ni-hat-3',
                    'color' => 'text-pink',
                    'nota' => 'texto',
                    'parent_id' => null,
                    'codapl' => 'CA',
                    'controller' => 'PrincipalController',
                    'action' => 'dashboard',
                ],
                [
                    'id' => 3,
                    'title' => 'Basicas',
                    'default_url' => null,
                    'icon' => 'ni ni-bullet-list-67',
                    'color' => 'text-black',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'CA',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 4,
                    'title' => 'Configuración',
                    'default_url' => null,
                    'icon' => 'ni ni-settings',
                    'color' => 'text-info',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'CA',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 5,
                    'title' => 'Solicitudes empleadores',
                    'default_url' => null,
                    'icon' => 'ni ni-briefcase-24',
                    'color' => 'text-warning',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'CA',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 6,
                    'title' => 'Solicitudes trabajadores',
                    'default_url' => null,
                    'icon' => 'ni ni-briefcase-24',
                    'color' => 'text-yellow',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'CA',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 7,
                    'title' => 'Movimientos administrador',
                    'default_url' => null,
                    'icon' => 'ni ni-active-40',
                    'color' => 'text-green',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'CA',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 8,
                    'title' => 'Movile',
                    'default_url' => null,
                    'icon' => 'ni ni-controller',
                    'color' => 'text-blue',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'CA',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 9,
                    'title' => 'Productos y servicios',
                    'default_url' => null,
                    'icon' => 'ni ni-box-2',
                    'color' => 'text-default',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'CA',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 10,
                    'title' => 'Reportes',
                    'default_url' => null,
                    'icon' => 'ni ni-bullet-list-67',
                    'color' => 'text-success',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'CA',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 11,
                    'title' => 'Usuarios',
                    'default_url' => null,
                    'icon' => 'fas fa-users',
                    'color' => 'text-orange',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'CA',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 12,
                    'title' => 'Configuración básica',
                    'default_url' => 'cajas/mercurio01/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '3',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio01Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 13,
                    'title' => 'Datos caja',
                    'default_url' => 'cajas/mercurio02/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '3',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio02Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 14,
                    'title' => 'Firmas',
                    'default_url' => 'cajas/mercurio03/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '3',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio03Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 15,
                    'title' => 'Tipos acceso',
                    'default_url' => 'cajas/mercurio06/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '3',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio06Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 16,
                    'title' => 'Documentos',
                    'default_url' => 'cajas/mercurio12/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '3',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio12Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 17,
                    'title' => 'Permisos por usuario',
                    'default_url' => 'cajas/gener42/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '3',
                    'codapl' => 'CA',
                    'controller' => 'Gener42Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 18,
                    'title' => 'Motivos rechazo',
                    'default_url' => 'cajas/mercurio11/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '4',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio11Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 19,
                    'title' => 'Tipos opciones',
                    'default_url' => 'cajas/mercurio09/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '4',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio09Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 20,
                    'title' => 'Oficinas',
                    'default_url' => 'cajas/mercurio04/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '4',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio04Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 21,
                    'title' => 'Galería',
                    'default_url' => 'cajas/mercurio26/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '4',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio26Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 22,
                    'title' => 'Empresas',
                    'default_url' => 'cajas/aprobacionemp/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '5',
                    'codapl' => 'CA',
                    'controller' => 'ApruebaEmpresaController',
                    'action' => 'index',
                ],
                [
                    'id' => 23,
                    'title' => 'Independientes',
                    'default_url' => 'cajas/aprobaindepen/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '5',
                    'codapl' => 'CA',
                    'controller' => 'ApruebaIndependienteController',
                    'action' => 'index',
                ],
                [
                    'id' => 24,
                    'title' => 'Pensionados',
                    'default_url' => 'cajas/aprobacionpen/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '5',
                    'codapl' => 'CA',
                    'controller' => 'ApruebaPensionadoController',
                    'action' => 'index',
                ],
                [
                    'id' => 25,
                    'title' => 'Facultativos',
                    'default_url' => 'cajas/aprobacionfac/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '5',
                    'codapl' => 'CA',
                    'controller' => 'ApruebaFacultativoController',
                    'action' => 'index',
                ],
                [
                    'id' => 26,
                    'title' => 'Madres comunitarias',
                    'default_url' => 'cajas/aprobacioncom/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '5',
                    'codapl' => 'CA',
                    'controller' => 'ApruebaMadresComunitariasController',
                    'action' => 'index',
                ],
                [
                    'id' => 28,
                    'title' => 'Datos basicos empresa',
                    'default_url' => 'cajas/actualizaemp/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '5',
                    'codapl' => 'CA',
                    'controller' => 'ApruebaUpEmpresaController',
                    'action' => 'index',
                ],
                [
                    'id' => 29,
                    'title' => 'Trabajadores',
                    'default_url' => 'cajas/aprobaciontra/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '6',
                    'codapl' => 'CA',
                    'controller' => 'ApruebaTrabajadoresController',
                    'action' => 'index',
                ],
                [
                    'id' => 30,
                    'title' => 'Conyuge',
                    'default_url' => 'cajas/aprobacioncon/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '6',
                    'codapl' => 'CA',
                    'controller' => 'ApruebaConyugeController',
                    'action' => 'index',
                ],
                [
                    'id' => 31,
                    'title' => 'Beneficiario',
                    'default_url' => 'cajas/aprobacionben/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '6',
                    'codapl' => 'CA',
                    'controller' => 'ApruebaBeneficiarioController',
                    'action' => 'index',
                ],
                [
                    'id' => 32,
                    'title' => 'Certificados',
                    'default_url' => 'cajas/aprobacioncer/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '6',
                    'codapl' => 'CA',
                    'controller' => 'ApruebaCertificadosController',
                    'action' => 'index',
                ],
                [
                    'id' => 33,
                    'title' => 'Datos basicos trabajador',
                    'default_url' => 'cajas/actualizatra/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '6',
                    'codapl' => 'CA',
                    'controller' => 'ApruebaUpTrabajadorController',
                    'action' => 'index',
                ],
                [
                    'id' => 34,
                    'title' => 'Consulta de auditoria',
                    'default_url' => 'cajas/auditoria/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '7',
                    'codapl' => 'CA',
                    'controller' => 'AuditoriaController',
                    'action' => 'index',
                ],
                [
                    'id' => 35,
                    'title' => 'Consulta activación masiva',
                    'default_url' => 'cajas/consulta/activacion_masiva',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '7',
                    'codapl' => 'CA',
                    'controller' => 'ConsultaController',
                    'action' => 'index',
                ],
                [
                    'id' => 36,
                    'title' => 'Reasignar solicitudes',
                    'default_url' => 'cajas/reasigna/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '7',
                    'codapl' => 'CA',
                    'controller' => 'ReasignaController',
                    'action' => 'index',
                ],
                [
                    'id' => 37,
                    'title' => 'Carga laboral',
                    'default_url' => 'cajas/consulta/carga_laboral',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '7',
                    'codapl' => 'CA',
                    'controller' => 'ConsultaController',
                    'action' => 'carga_laboral',
                ],
                [
                    'id' => 38,
                    'title' => 'Indicadores',
                    'default_url' => 'cajas/consulta/indicadores',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '7',
                    'codapl' => 'CA',
                    'controller' => 'ConsultaController',
                    'action' => 'indicadores',
                ],
                [
                    'id' => 39,
                    'title' => 'Administración básica',
                    'default_url' => 'cajas/mercurio50/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',  //para movile
                    'codapl' => 'CA',
                    'controller' => 'Mercurio50Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 40,
                    'title' => 'Promociones',
                    'default_url' => 'cajas/mercurio57/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio57Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 41,
                    'title' => 'Turismo',
                    'default_url' => 'cajas/mercurio72/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio72Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 42,
                    'title' => 'Educación',
                    'default_url' => 'cajas/mercurio73/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio73Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 43,
                    'title' => 'Recreación',
                    'default_url' => 'cajas/mercurio74/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio74Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 44,
                    'title' => 'Destacadas',
                    'default_url' => 'cajas/mercurio53/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio53Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 45,
                    'title' => 'Categorias',
                    'default_url' => 'cajas/mercurio51/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio51Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 46,
                    'title' => 'Areas',
                    'default_url' => 'cajas/mercurio55/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio55Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 47,
                    'title' => 'Menu',
                    'default_url' => 'cajas/mercurio52/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio52Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 48,
                    'title' => 'Insfraestruturas',
                    'default_url' => 'cajas/mercurio56/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio56Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 49,
                    'title' => 'Clasificacion comercios',
                    'default_url' => 'cajas/mercurio67/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio67Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 50,
                    'title' => 'Comercios',
                    'default_url' => 'cajas/mercurio65/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '8',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio65Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 51,
                    'title' => 'Lista de productos',
                    'default_url' => 'cajas/admproductos/lista',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '9',
                    'codapl' => 'CA',
                    'controller' => 'AdmproductosController',
                    'action' => 'lista',
                ],
                [
                    'id' => 52,
                    'title' => 'Complemento nutricional',
                    'default_url' => 'cajas/admproductos/aplicados/27',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '9',
                    'codapl' => 'CA',
                    'controller' => 'AdmproductosController',
                    'action' => 'aplicados',
                ],
                [
                    'id' => 53,
                    'title' => 'Usuarios enlinea',
                    'default_url' => 'cajas/usuario/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => null,
                    'parent_id' => '11',
                    'codapl' => 'CA',
                    'controller' => 'UsuarioController',
                    'action' => 'index',
                ],
                [
                    'id' => 54,
                    'title' => 'Requerido por trabajador',
                    'default_url' => 'cajas/mercurio13/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '3',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio13Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 55,
                    'title' => 'Requerido por empresa',
                    'default_url' => 'cajas/mercurio14/index',
                    'icon' => null,
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => '3',
                    'codapl' => 'CA',
                    'controller' => 'Mercurio14Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 56,
                    'title' => 'Reportes solicitudes',
                    'default_url' => 'cajas/reportesol/index',
                    'icon' => 'ni ni-bullet-list-67',
                    'color' => 'text-success',
                    'nota' => null,
                    'parent_id' => '10',
                    'codapl' => 'CA',
                    'controller' => 'ReportesolController',
                    'action' => 'index',
                ],
            ];

            $menu_mercurio = [
                [
                    'id' => 178,
                    'title' => 'Inicio',
                    'default_url' => 'mercurio/principal/index',
                    'icon' => 'fas fa-home',
                    'color' => 'text-primary',
                    'nota' => 'texto',
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => 'PrincipalController',
                    'action' => 'index',
                ],
                [
                    'id' => 179,
                    'title' => 'Reportar errores del sistema',
                    'default_url' => 'mercurio/notificaciones/index',
                    'icon' => 'fas fa-box',
                    'color' => 'text-red',
                    'nota' => 'texto',
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => 'NotificacionesController',
                    'action' => 'index',
                ],
                [
                    'id' => 180,
                    'title' => 'Productos y servicios',
                    'default_url' => null,
                    'icon' => 'ni ni-briefcase-24',
                    'color' => 'text-orange',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 181,
                    'title' => 'Complemento nutricional',
                    'default_url' => 'mercurio/productos/complemento_nutricional',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '180',
                    'codapl' => 'ME',
                    'controller' => 'ProductosController',
                    'action' => 'complementoNutricional',
                ],
                [
                    'id' => 182,
                    'title' => 'Consultas',
                    'default_url' => null,
                    'icon' => 'ni ni-collection',
                    'color' => 'text-red',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 183,
                    'title' => 'Consulta nucleo familiar',
                    'default_url' => 'mercurio/subsidio/consulta_nucleo_view',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '182',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasTrabajadorController',
                    'action' => 'consultaNucleoView',
                ],
                [
                    'id' => 184,
                    'title' => 'Consulta giro',
                    'default_url' => 'mercurio/subsidio/consulta_giro_view',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '182',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasTrabajadorController',
                    'action' => 'consultaGiro',
                ],
                [
                    'id' => 185,
                    'title' => 'Consulta no giro',
                    'default_url' => 'mercurio/subsidio/consulta_no_giro_view',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '182',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasTrabajadorController',
                    'action' => 'consultaNoGiro',
                ],
                [
                    'id' => 186,
                    'title' => 'Consulta planilla',
                    'default_url' => 'mercurio/subsidio/consulta_planilla_trabajador_view',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '182',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasTrabajadorController',
                    'action' => 'consultaPlanillaTrabajadorView',
                ],
                [
                    'id' => 187,
                    'title' => 'Consulta saldo',
                    'default_url' => 'mercurio/subsidio/consulta_tarjeta',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '182',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasTrabajadorController',
                    'action' => 'consultaTarjeta',
                ],
                [
                    'id' => 188,
                    'title' => '(T) Afiliación',
                    'default_url' => null,
                    'icon' => 'ni ni-active-40',
                    'color' => 'text-info',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 189,
                    'title' => 'Actualización trabajador básicos',
                    'default_url' => 'mercurio/actualizadatostra/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '188',
                    'codapl' => 'ME',
                    'controller' => 'ActualizaTrabajadorController',
                    'action' => 'index',
                ],
                [
                    'id' => 190,
                    'title' => '(T) Afiliación conyuge',
                    'default_url' => 'mercurio/conyuge/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '188',
                    'codapl' => 'ME',
                    'controller' => 'ConyugeController',
                    'action' => 'index',
                ],
                [
                    'id' => 191,
                    'title' => '(T) Afiliación beneficiario',
                    'default_url' => 'mercurio/beneficiario/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '188',
                    'codapl' => 'ME',
                    'controller' => 'BeneficiarioController',
                    'action' => 'index',
                ],
                [
                    'id' => 192,
                    'title' => '(T) Presentación certificados',
                    'default_url' => 'mercurio/certificados/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '188',
                    'codapl' => 'ME',
                    'controller' => 'CertificadosController',
                    'action' => 'index',
                ],
                [
                    'id' => 193,
                    'title' => 'Certificados',
                    'default_url' => null,
                    'icon' => 'ni ni-paper-diploma',
                    'color' => 'text-green',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 194,
                    'title' => 'Certificado de afiliación',
                    'default_url' => 'mercurio/subsidio/certificado_afiliacion',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '193',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasTrabajadorController',
                    'action' => 'certificadoAfiliacion',
                ],
                [
                    'id' => 195,
                    'title' => 'Cuenta usuario',
                    'default_url' => null,
                    'icon' => 'fas fa-user',
                    'color' => 'text-orange',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 196,
                    'title' => 'Perfil usuario',
                    'default_url' => 'mercurio/usuario/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => null,
                    'parent_id' => '195',
                    'codapl' => 'ME',
                    'controller' => 'UsuarioController',
                    'action' => 'index',
                ],
                [
                    'id' => 197,
                    'title' => 'Buscar historial',
                    'default_url' => 'mercurio/subsidio/historial',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '195',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasTrabajadorController',
                    'action' => 'historial',
                ],
                [
                    'id' => 198,
                    'title' => 'Firma digital',
                    'default_url' => 'mercurio/firmas/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '195',
                    'codapl' => 'ME',
                    'controller' => 'FirmasController',
                    'action' => 'index',
                ],
                [
                    'id' => 200,
                    'title' => 'Estadística',
                    'default_url' => 'mercurio/principal/dashboard_empresa',
                    'icon' => 'ni ni-hat-3',
                    'color' => 'text-yellow',
                    'nota' => 'texto',
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => 'PrincipalController',
                    'action' => 'dashboardEmpresa',
                ],
                [
                    'id' => 202,
                    'title' => 'Consultas generales',
                    'default_url' => null,
                    'icon' => 'ni ni-collection',
                    'color' => 'text-red',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 203,
                    'title' => 'Consulta trabajadores',
                    'default_url' => 'mercurio/subsidioemp/consulta_trabajadores_view',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '202',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasEmpresaController',
                    'action' => 'consultaTrabajadoresView',
                ],
                [
                    'id' => 204,
                    'title' => 'Consulta giro',
                    'default_url' => 'mercurio/subsidioemp/consulta_giro_view',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '202',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasEmpresaController',
                    'action' => 'consultaGiroView',
                ],
                [
                    'id' => 205,
                    'title' => 'Consulta mora presunta',
                    'default_url' => 'mercurio/subsidioemp/consulta_mora_presunta',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '202',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasEmpresaController',
                    'action' => 'consultaMoraPresunta',
                ],
                [
                    'id' => 206,
                    'title' => 'Consulta nomina',
                    'default_url' => 'mercurio/subsidioemp/consulta_nomina_view',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '202',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasEmpresaController',
                    'action' => 'consultaNominaView',
                ],
                [
                    'id' => 207,
                    'title' => 'Consulta aportes',
                    'default_url' => 'mercurio/subsidioemp/consulta_aportes_view',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '202',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasEmpresaController',
                    'action' => 'consultaAportesView',
                ],
                [
                    'id' => 208,
                    'title' => '(E) Afiliación',
                    'default_url' => null,
                    'icon' => 'ni ni-active-40',
                    'color' => 'text-info',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 209,
                    'title' => 'Actualización datos empresa',
                    'default_url' => 'mercurio/actualizadatos/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '208',
                    'codapl' => 'ME',
                    'controller' => 'ActualizaEmpresaController',
                    'action' => 'index',
                ],
                [
                    'id' => 210,
                    'title' => '(E) Afiliación de trabajador',
                    'default_url' => 'mercurio/trabajador/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '208',
                    'codapl' => 'ME',
                    'controller' => 'TrabajadorController',
                    'action' => 'index',
                ],
                [
                    'id' => 213,
                    'title' => 'Certificados',
                    'default_url' => null,
                    'icon' => 'ni ni-paper-diploma',
                    'color' => 'text-green',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 214,
                    'title' => 'Certificado de afiliación',
                    'default_url' => 'mercurio/subsidioemp/certificado_afiliacion',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '213',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasEmpresaController',
                    'action' => 'certificadoAfiliacionView',
                ],
                [
                    'id' => 215,
                    'title' => 'Certificado para trabajador',
                    'default_url' => 'mercurio/subsidioemp/certificado_para_trabajador',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '213',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasEmpresaController',
                    'action' => 'certificadoParaTrabajadorView',
                ],
                [
                    'id' => 216,
                    'title' => 'Cuenta usuario',
                    'default_url' => null,
                    'icon' => 'fas fa-user',
                    'color' => 'text-orange',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 218,
                    'title' => 'Buscar historial',
                    'default_url' => 'mercurio/subsidioemp/historial',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '216',
                    'codapl' => 'ME',
                    'controller' => 'ConsultasEmpresaController',
                    'action' => 'historial',
                ],
                [
                    'id' => 223,
                    'title' => 'Afiliación empresa',
                    'default_url' => 'mercurio/empresa/index',
                    'icon' => 'ni ni-bullet-list-67',
                    'color' => 'text-blue',
                    'nota' => 'texto',
                    'parent_id' => '208',
                    'codapl' => 'ME',
                    'controller' => 'EmpresaController',
                    'action' => 'index',
                ],
                [
                    'id' => 224,
                    'title' => 'Afiliación independientes',
                    'default_url' => 'mercurio/independiente/index',
                    'icon' => 'ni ni-bullet-list-67',
                    'color' => 'text-blue',
                    'nota' => 'texto',
                    'parent_id' => '208',
                    'codapl' => 'ME',
                    'controller' => 'IndependienteController',
                    'action' => 'index',
                ],
                [
                    'id' => 225,
                    'title' => 'Afiliación pensionados',
                    'default_url' => 'mercurio/pensionado/index',
                    'icon' => 'ni ni-bullet-list-67',
                    'color' => 'text-blue',
                    'nota' => 'texto',
                    'parent_id' => '208',
                    'codapl' => 'ME',
                    'controller' => 'PensionadoController',
                    'action' => 'index',
                ],
                [
                    'id' => 226,
                    'title' => 'Afiliación facultativos',
                    'default_url' => 'mercurio/facultativo/index',
                    'icon' => 'ni ni-bullet-list-67',
                    'color' => 'text-blue',
                    'nota' => 'texto',
                    'parent_id' => '208',
                    'codapl' => 'ME',
                    'controller' => 'FacultativoController',
                    'action' => 'index',
                ],
                [
                    'id' => 227,
                    'title' => 'Cuenta usuario',
                    'default_url' => null,
                    'icon' => 'fas fa-user',
                    'color' => 'text-orange',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 229,
                    'title' => 'Buscar historial',
                    'default_url' => 'mercurio/movimientos/historial',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '227',
                    'codapl' => 'ME',
                    'controller' => 'MovimientosController',
                    'action' => 'historial',
                ],
                [
                    'id' => 233,
                    'title' => 'Foniñez modulo',
                    'default_url' => null,
                    'icon' => 'fas fa-child',
                    'color' => 'text-yellow',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 234,
                    'title' => 'Beneficiarios',
                    'default_url' => 'mercurio/mercurio83/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '233',
                    'codapl' => 'ME',
                    'controller' => 'Mercurio83Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 235,
                    'title' => 'Eventos',
                    'default_url' => 'mercurio/mercurio80/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '233',
                    'codapl' => 'ME',
                    'controller' => 'Mercurio80Controller',
                    'action' => 'index',
                ],
                [
                    'id' => 236,
                    'title' => 'Cuenta usuario',
                    'default_url' => null,
                    'icon' => 'fas fa-user',
                    'color' => 'text-orange',
                    'nota' => null,
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => null,
                    'action' => null,
                ],
                [
                    'id' => 240,
                    'title' => 'Mi empresa',
                    'default_url' => 'mercurio/empresa/miempresa',
                    'icon' => 'fas fa-building',
                    'color' => 'text-black',
                    'nota' => 'texto',
                    'parent_id' => null,
                    'codapl' => 'ME',
                    'controller' => 'EmpresaController',
                    'action' => 'miempresa',
                ],
                [
                    'id' => 241,
                    'title' => '(E) Afiliación conyuge',
                    'default_url' => 'mercurio/conyuge/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '208',
                    'codapl' => 'ME',
                    'controller' => 'ConyugeController',
                    'action' => 'index',
                ],
                [
                    'id' => 242,
                    'title' => '(E) Afiliación beneficiario',
                    'default_url' => 'mercurio/beneficiario/index',
                    'icon' => null,
                    'color' => '',
                    'nota' => 'texto',
                    'parent_id' => '208',
                    'codapl' => 'ME',
                    'controller' => 'BeneficiarioController',
                    'action' => 'index',
                ]
            ];

            foreach ($menu_mercurio as $item1) {
                MenuItem::create($item1);
            }

            foreach ($menu_caja as $item2) {
                MenuItem::create($item2);
            }
        });
    }

    /**
     * Elimina los registros existentes para permitir re-ejecuciones idempotentes.
     */
    protected function limpiarTabla(): void
    {
        DB::statement(sprintf('DELETE FROM %s', self::TABLE));
    }
}
