<?php

use App\Services\Tag;
?>
<div class="card shadow-sm border-0 rounded-4 mb-4" style="max-width: 800px; margin: 0rem auto;">
    <div class="card-header py-2 rounded-top">
        <h4 class="text-center text-primary mb-0">Comfaca en línea</h4>
        <?= Tag::image("logo-min.png", "class: img-fluid mx-auto d-block mb-4 rounded", "style: width:180px"); ?>

        <p class="text-left mb-4">
            <span class='text-info'>Comfaca en línea</span> es la plataforma principal de afiliación, gestión y consulta disponibles para los usuarios afiliados y personas residentes en el departamento del Caquetá.
        </p>
    </div>
    <div class="card-body p-4">

        <div class="rounded-3 p-3">
            <div class="list-group">
                <div class="list-group-item border-0 rounded-2 mb-2">
                    <p class="mb-0" style="color: #555;">
                        Si no estás afiliado, debes hacer el registro por la opción <span class='text-danger fw-semibold'>(Registrar En Plataforma)</span>,
                        con los datos requeridos para dar inicio al proceso de afiliación. El sistema se encargará de crear un tipo de afiliado: <span class='text-danger fw-semibold'>(Particular)</span>,
                        que le permite hacer las solicitudes para afiliación de forma segura.
                    </p>
                </div>
                <div class="list-group-item border-0 rounded-2 mb-2">
                    <p class="mb-0" style="color: #555;">
                        Si has olvidado la clave de usuario, puedes hacer recuperación de la misma por la opción <span class='text-danger fw-semibold'>(Pulsar si olvido su clave aquí)</span>,
                        disponible en la parte inferior del inicio de sesión.
                    </p>
                </div>
                <div class="list-group-item border-0 rounded-2">
                    <p class="mb-0" style="color: #555;">
                        Si ya estás afiliado, pero no dispones de una clave de acceso, puedes usar la opción de <span class='text-danger fw-semibold'>(Pulsar cuando no tienes clave aquí)</span>,
                        disponible en la parte inferior del inicio de sesión.
                    </p>
                </div>

                <div class="list-group-item border-0 rounded-2">
                    <p class="mb-0" style="color: #555;">
                        Si ya estás afiliado, pero la cuenta de correo electrónico no es la correcta, puedes solicitar el cambio de correo electrónico por la opción <span class='text-danger fw-semibold'>(Pulsar para cambiar su correo electrónico)</span>,
                        disponible en la parte inferior del inicio de sesión.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .fw-semibold {
        text-shadow: none;
        font-size: 1rem;
    }
</style>
