<?php

namespace App\Services\Entities;

use App\Services\Validator\ValidatorTrait;

class ConyugeEntity
{
    use ValidatorTrait;

    protected $fillable = [
        'cedtra',
        'cedcon',
        'fecafi',
        'recsub',
        'comper',
        'ruaf',
        'numrua',
        'fosfec',
        'fecrua',
        'coddoc',
        'priape',
        'segape',
        'prinom',
        'segnom',
        'direccion',
        'telefono',
        'email',
        'codzon',
        'codcaj',
        'codocu',
        'nivedu',
        'captra',
        'salario',
        'tipsal',
        'fecsal',
        'tippag',
        'codcue',
        'ofides',
        'codgru',
        'codban',
        'numcue',
        'tipcue',
        'sexo',
        'estciv',
        'fecnac',
        'ciunac',
        'estado',
        'fecest',
        'numtar',
        'giass',
        'usuario',
        'fecact',
        'empresalab',
    ];

    protected function getRules()
    {
        return [
            'cedtra' => ['type' => 'string', 'max' => 18, 'is_null' => false],
            'cedcon' => ['type' => 'string', 'max' => 20, 'is_null' => false],
            'fecafi' => ['type' => 'date', 'is_null' => false],
            'recsub' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'comper' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'ruaf' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'numrua' => ['type' => 'integer', 'is_null' => true],
            'fosfec' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'fecrua' => ['type' => 'date', 'is_null' => true],
            'coddoc' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'priape' => ['type' => 'string', 'max' => 20, 'is_null' => false],
            'segape' => ['type' => 'string', 'max' => 30, 'is_null' => true],
            'prinom' => ['type' => 'string', 'max' => 30, 'is_null' => false],
            'segnom' => ['type' => 'string', 'max' => 20, 'is_null' => true],
            'direccion' => ['type' => 'string', 'max' => 40, 'is_null' => true],
            'telefono' => ['type' => 'string', 'max' => 20, 'is_null' => true],
            'email' => ['type' => 'string', 'max' => 50, 'is_null' => true],
            'codzon' => ['type' => 'string', 'max' => 9, 'is_null' => false],
            'codcaj' => ['type' => 'string', 'max' => 2, 'is_null' => true],
            'codocu' => ['type' => 'string', 'max' => 2, 'is_null' => true],
            'nivedu' => ['type' => 'string', 'max' => 2, 'is_null' => false],
            'captra' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'salario' => ['type' => 'integer', 'is_null' => false],
            'tipsal' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'fecsal' => ['type' => 'date', 'is_null' => true],
            'tippag' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'codcue' => ['type' => 'string', 'max' => 3, 'is_null' => true],
            'ofides' => ['type' => 'string', 'max' => 4, 'is_null' => true],
            'codgru' => ['type' => 'string', 'max' => 3, 'is_null' => true],
            'codban' => ['type' => 'string', 'max' => 5, 'is_null' => true],
            'numcue' => ['type' => 'string', 'max' => 17, 'is_null' => true],
            'tipcue' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'sexo' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'estciv' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'fecnac' => ['type' => 'date', 'is_null' => false],
            'ciunac' => ['type' => 'string', 'max' => 5, 'is_null' => true],
            'estado' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'fecest' => ['type' => 'date', 'is_null' => true],
            'numtar' => ['type' => 'string', 'max' => 15, 'is_null' => true],
            'giass' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'usuario' => ['type' => 'string', 'max' => 10, 'is_null' => true],
            'fecact' => ['type' => 'date', 'is_null' => true],
            'empresalab' => ['type' => 'string', 'max' => 100, 'is_null' => true],
        ];
    }
}
