<?php

namespace App\Services\Entities;

use App\Services\Validator\ValidatorTrait;

class EmpresaEntity
{
    use ValidatorTrait;

    protected $fillable = array(
        'nit',
        'digver',
        'tipper',
        'coddoc',
        'razsoc',
        'priape',
        'segape',
        'prinom',
        'segnom',
        'nomemp',
        'sigla',
        'cedrep',
        'repleg',
        'jefper',
        'cedpro',
        'nompro',
        'direccion',
        'codciu',
        'telefono',
        'fax',
        'email',
        'codzon',
        'dirpri',
        'telpri',
        'ciupri',
        'ofiafi',
        'codase',
        'calemp',
        'tipemp',
        'tipsoc',
        'tipapo',
        'forpre',
        'pymes',
        'contratista',
        'colegio',
        'todmes',
        'matmer',
        'codact',
        'codind',
        'feccer',
        'actapr',
        'fecapr',
        'fecafi',
        'fecsis',
        'estado',
        'resest',
        'codest',
        'fecest',
        'tottra',
        'totapo',
        'totcon',
        'tothij',
        'tother',
        'totpad',
        'fecmer',
        'tipdur',
        'feccor',
        'feccam',
        'valmor',
        'permor',
        'fosfec',
        'telt',
        'telr',
        'mailr',
        'mailt',
        'giass',
        'actugp',
        'correo',
        'nota',
        'coddocrepleg',
        'priaperepleg',
        'segaperepleg',
        'prinomrepleg',
        'segnomrepleg',
        'codcaj',
        'traapo',
        'valapo',
        'tietra',
        'tratot'
    );

    protected function getRules()
    {
        return array(
            'nit' => array('type' => 'string', 'max' => 16),
            'digver' => array('type' => 'string', 'max' => 1),
            'tipper' => array('type' => 'string', 'max' => 1),
            'coddoc' => array('type' => 'string', 'max' => 1),
            'razsoc' => array('type' => 'string', 'max' => 180),
            'priape' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'segape' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'prinom' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'segnom' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'nomemp' => array('type' => 'string', 'max' => 180, 'is_null' => true),
            'sigla' => array('type' => 'string', 'max' => 30, 'is_null' => true),
            'cedrep' => array('type' => 'string', 'max' => 13, 'is_null' => true),
            'repleg' => array('type' => 'string', 'max' => 140, 'is_null' => true),
            'jefper' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'cedpro' => array('type' => 'string', 'max' => 13, 'is_null' => true),
            'nompro' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'direccion' => array('type' => 'string', 'max' => 120, 'is_null' => true),
            'codciu' => array('type' => 'string', 'max' => 5, 'is_null' => true),
            'telefono' => array('type' => 'string', 'max' => 20, 'is_null' => true),
            'fax' => array('type' => 'string', 'max' => 13, 'required' => false, 'is_null' => true),
            'email' => array('type' => 'email', 'max' => 100, 'is_null' => true),
            'codzon' => array('type' => 'string', 'max' => 9),
            'dirpri' => array('type' => 'string', 'max' => 120, 'is_null' => true),
            'telpri' => array('type' => 'string', 'max' => 20, 'is_null' => true),
            'ciupri' => array('type' => 'string', 'max' => 5, 'is_null' => true),
            'ofiafi' => array('type' => 'string', 'max' => 2),
            'codase' => array('type' => 'string', 'max' => 2),
            'calemp' => array('type' => 'string', 'max' => 1),
            'tipemp' => array('type' => 'string', 'max' => 1),
            'tipsoc' => array('type' => 'string', 'max' => 2),
            'tipapo' => array('type' => 'string', 'max' => 1),
            'forpre' => array('type' => 'string', 'max' => 1),
            'pymes' => array('type' => 'string', 'max' => 1),
            'contratista' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'colegio' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'todmes' => array('type' => 'string', 'max' => 1),
            'matmer' => array('type' => 'string', 'max' => 12, 'is_null' => true),
            'codact' => array('type' => 'string', 'max' => 6),
            'codind' => array('type' => 'string', 'max' => 2),
            'feccer' => array('type' => 'date', 'is_null' => false),
            'actapr' => array('type' => 'string', 'max' => 50),
            'fecapr' => array('type' => 'date'),
            'fecafi' => array('type' => 'date'),
            'fecsis' => array('type' => 'date'),
            'estado' => array('type' => 'string', 'max' => 1),
            'resest' => array('type' => 'string', 'max' => 15, 'is_null' => true),
            'codest' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'fecest' => array('type' => 'date', 'is_null' => true),
            'tottra' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'totapo' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'totcon' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'tothij' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'tother' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'totpad' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'fecmer' => array('type' => 'date', 'is_null' => true),
            'tipdur' => array('type' => 'string', 'max' => 1),
            'feccor' => array('type' => 'date', 'is_null' => true),
            'feccam' => array('type' => 'date', 'is_null' => true),
            'valmor' => array('type' => 'string', 'max' => 50, 'is_null' => true),
            'permor' => array('type' => 'string', 'max' => 150, 'is_null' => true),
            'fosfec' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'telt' => array('type' => 'string', 'max' => 20, 'is_null' => true),
            'telr' => array('type' => 'string', 'max' => 20, 'is_null' => true),
            'mailr' => array('type' => 'email', 'max' => 100, 'is_null' => true),
            'mailt' => array('type' => 'email', 'max' => 100, 'is_null' => true),
            'giass' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'actugp' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'correo' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'nota' => array('type' => 'string', 'max' => 255, 'is_null' => true),
            'coddocrepleg' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'priaperepleg' => array('type' => 'string', 'max' => 25, 'is_null' => true),
            'segaperepleg' => array('type' => 'string', 'max' => 25, 'is_null' => true),
            'prinomrepleg' => array('type' => 'string', 'max' => 25, 'is_null' => true),
            'segnomrepleg' => array('type' => 'string', 'max' => 25, 'is_null' => true),
            'codcaj' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'traapo' => array('type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => false),
            'valapo' => array('type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => false),
            'tietra' => array('type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => false),
            'tratot' => array('type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => false),
        );
    }
}
