<?php

namespace App\Services\Entities;

use App\Services\Validator\ValidatorTrait;

class EmpresaEntity
{
    use ValidatorTrait;

    protected $fillable = [
        'nit',
        'digver',
        'tipper',
        'coddoc',
        'razsoc',
        'priape',
        'segape',
        'prinom',
        'segnom',
        'nomemp',
        'sigla',
        'cedrep',
        'repleg',
        'jefper',
        'cedpro',
        'nompro',
        'direccion',
        'codciu',
        'telefono',
        'fax',
        'email',
        'codzon',
        'dirpri',
        'telpri',
        'ciupri',
        'ofiafi',
        'codase',
        'calemp',
        'tipemp',
        'tipsoc',
        'tipapo',
        'forpre',
        'pymes',
        'contratista',
        'colegio',
        'todmes',
        'matmer',
        'codact',
        'codind',
        'feccer',
        'actapr',
        'fecapr',
        'fecafi',
        'fecsis',
        'estado',
        'resest',
        'codest',
        'fecest',
        'tottra',
        'totapo',
        'totcon',
        'tothij',
        'tother',
        'totpad',
        'fecmer',
        'tipdur',
        'feccor',
        'feccam',
        'valmor',
        'permor',
        'fosfec',
        'telt',
        'telr',
        'mailr',
        'mailt',
        'giass',
        'actugp',
        'correo',
        'nota',
        'coddocrepleg',
        'priaperepleg',
        'segaperepleg',
        'prinomrepleg',
        'segnomrepleg',
        'codcaj',
        'traapo',
        'valapo',
        'tietra',
        'tratot',
    ];

    protected function getRules()
    {
        return [
            'nit' => ['type' => 'string', 'max' => 16],
            'digver' => ['type' => 'string', 'max' => 1],
            'tipper' => ['type' => 'string', 'max' => 1],
            'coddoc' => ['type' => 'string', 'max' => 1],
            'razsoc' => ['type' => 'string', 'max' => 180],
            'priape' => ['type' => 'string', 'max' => 40, 'is_null' => true],
            'segape' => ['type' => 'string', 'max' => 40, 'is_null' => true],
            'prinom' => ['type' => 'string', 'max' => 40, 'is_null' => true],
            'segnom' => ['type' => 'string', 'max' => 40, 'is_null' => true],
            'nomemp' => ['type' => 'string', 'max' => 180, 'is_null' => true],
            'sigla' => ['type' => 'string', 'max' => 30, 'is_null' => true],
            'cedrep' => ['type' => 'string', 'max' => 13, 'is_null' => true],
            'repleg' => ['type' => 'string', 'max' => 140, 'is_null' => true],
            'jefper' => ['type' => 'string', 'max' => 40, 'is_null' => true],
            'cedpro' => ['type' => 'string', 'max' => 13, 'is_null' => true],
            'nompro' => ['type' => 'string', 'max' => 40, 'is_null' => true],
            'direccion' => ['type' => 'string', 'max' => 120, 'is_null' => true],
            'codciu' => ['type' => 'string', 'max' => 5, 'is_null' => true],
            'telefono' => ['type' => 'string', 'max' => 20, 'is_null' => true],
            'fax' => ['type' => 'string', 'max' => 13, 'required' => false, 'is_null' => true],
            'email' => ['type' => 'email', 'max' => 100, 'is_null' => true],
            'codzon' => ['type' => 'string', 'max' => 9],
            'dirpri' => ['type' => 'string', 'max' => 120, 'is_null' => true],
            'telpri' => ['type' => 'string', 'max' => 20, 'is_null' => true],
            'ciupri' => ['type' => 'string', 'max' => 5, 'is_null' => true],
            'ofiafi' => ['type' => 'string', 'max' => 2],
            'codase' => ['type' => 'string', 'max' => 2],
            'calemp' => ['type' => 'string', 'max' => 1],
            'tipemp' => ['type' => 'string', 'max' => 1],
            'tipsoc' => ['type' => 'string', 'max' => 2],
            'tipapo' => ['type' => 'string', 'max' => 1],
            'forpre' => ['type' => 'string', 'max' => 1],
            'pymes' => ['type' => 'string', 'max' => 1],
            'contratista' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'colegio' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'todmes' => ['type' => 'string', 'max' => 1],
            'matmer' => ['type' => 'string', 'max' => 12, 'is_null' => true],
            'codact' => ['type' => 'string', 'max' => 6],
            'codind' => ['type' => 'string', 'max' => 2],
            'feccer' => ['type' => 'date', 'is_null' => false],
            'actapr' => ['type' => 'string', 'max' => 50],
            'fecapr' => ['type' => 'date'],
            'fecafi' => ['type' => 'date'],
            'fecsis' => ['type' => 'date'],
            'estado' => ['type' => 'string', 'max' => 1],
            'resest' => ['type' => 'string', 'max' => 15, 'is_null' => true],
            'codest' => ['type' => 'string', 'max' => 2, 'is_null' => true],
            'fecest' => ['type' => 'date', 'is_null' => true],
            'tottra' => ['type' => 'rangelength', 'min' => 1, 'max' => 11],
            'totapo' => ['type' => 'rangelength', 'min' => 1, 'max' => 11],
            'totcon' => ['type' => 'rangelength', 'min' => 1, 'max' => 11],
            'tothij' => ['type' => 'rangelength', 'min' => 1, 'max' => 11],
            'tother' => ['type' => 'rangelength', 'min' => 1, 'max' => 11],
            'totpad' => ['type' => 'rangelength', 'min' => 1, 'max' => 11],
            'fecmer' => ['type' => 'date', 'is_null' => true],
            'tipdur' => ['type' => 'string', 'max' => 1],
            'feccor' => ['type' => 'date', 'is_null' => true],
            'feccam' => ['type' => 'date', 'is_null' => true],
            'valmor' => ['type' => 'string', 'max' => 50, 'is_null' => true],
            'permor' => ['type' => 'string', 'max' => 150, 'is_null' => true],
            'fosfec' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'telt' => ['type' => 'string', 'max' => 20, 'is_null' => true],
            'telr' => ['type' => 'string', 'max' => 20, 'is_null' => true],
            'mailr' => ['type' => 'email', 'max' => 100, 'is_null' => true],
            'mailt' => ['type' => 'email', 'max' => 100, 'is_null' => true],
            'giass' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'actugp' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'correo' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'nota' => ['type' => 'string', 'max' => 255, 'is_null' => true],
            'coddocrepleg' => ['type' => 'string', 'max' => 2, 'is_null' => true],
            'priaperepleg' => ['type' => 'string', 'max' => 25, 'is_null' => true],
            'segaperepleg' => ['type' => 'string', 'max' => 25, 'is_null' => true],
            'prinomrepleg' => ['type' => 'string', 'max' => 25, 'is_null' => true],
            'segnomrepleg' => ['type' => 'string', 'max' => 25, 'is_null' => true],
            'codcaj' => ['type' => 'string', 'max' => 2, 'is_null' => true],
            'traapo' => ['type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => false],
            'valapo' => ['type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => false],
            'tietra' => ['type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => false],
            'tratot' => ['type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => false],
        ];
    }
}
