<?php

namespace App\Services\Entities;

use App\Services\Validator\ValidatorTrait;

class IndependienteEntity
{
    use ValidatorTrait;

    protected $fillable = array(
        'nit',
        'digver',
        'tipper',
        'coddoc',
        'razsoc',
        'priape',
        'segape',
        'prinom',
        'segnom',
        'nomemp',
        'sigla',
        'cedrep',
        'repleg',
        'jefper',
        'cedpro',
        'nompro',
        'direccion',
        'codciu',
        'telefono',
        'fax',
        'email',
        'codzon',
        'dirpri',
        'telpri',
        'ciupri',
        'ofiafi',
        'codase',
        'calemp',
        'tipemp',
        'tipsoc',
        'tipapo',
        'forpre',
        'pymes',
        'contratista',
        'colegio',
        'todmes',
        'matmer',
        'codact',
        'codind',
        'feccer',
        'actapr',
        'fecapr',
        'fecafi',
        'fecsis',
        'estado',
        'resest',
        'codest',
        'fecest',
        'tottra',
        'totapo',
        'totcon',
        'tothij',
        'tother',
        'totpad',
        'fecmer',
        'tipdur',
        'feccor',
        'feccam',
        'valmor',
        'permor',
        'fosfec',
        'telt',
        'telr',
        'mailr',
        'mailt',
        'giass',
        'actugp',
        'correo',
        'nota',
        'coddocrepleg',
        'priaperepleg',
        'segaperepleg',
        'prinomrepleg',
        'segnomrepleg',
        'codcaj',
        'codsuc',
        'codlis',
        'cedtra',
        'rural',
        'agro',
        'cabhog',
        'captra',
        'tipdis',
        'horas',
        'salario',
        'tipsal',
        'fecsal',
        'sexo',
        'estciv',
        'tipcon',
        'feccon',
        'trasin',
        'vivienda',
        'nivedu',
        'tipcot',
        'vendedor',
        'empleador',
        'tippag',
        'codcue',
        'ofides',
        'codgru',
        'codban',
        'numcue',
        'tipcue',
        'feccar',
        'codcat',
        'fecnac',
        'ciunac',
        'fecpre',
        'giro',
        'giro2',
        'codgir',
        'codgir2',
        'carnet',
        'benef',
        'ruaf',
        'ruasub',
        'nota',
        'numtar',
        'fecrua',
        'fosfec',
        'fecact',
        'tipjor',
        'usuario',
        'correo',
        'tottra',
        'cargo',
        'orisex',
        'dirlab',
        'ruralt',
        'ciulab',
        'pais',
        'facvul',
        'peretn',
        'fecha_giro',
        'resguardo_id',
        'pub_indigena_id',
        'traapo',
        'valapo',
        'tietra',
        'tratot'
    );

    protected function getRules()
    {
        return array(
            'nit' => array('type' => 'string', 'max' => 16),
            'digver' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'tipper' => array('type' => 'string', 'max' => 1),
            'coddoc' => array('type' => 'string', 'max' => 1),
            'razsoc' => array('type' => 'string', 'max' => 180),
            'priape' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'segape' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'prinom' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'segnom' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'nomemp' => array('type' => 'string', 'max' => 180, 'is_null' => true),
            'sigla' => array('type' => 'string', 'max' => 30, 'is_null' => true),
            'cedrep' => array('type' => 'string', 'max' => 13, 'is_null' => true),
            'repleg' => array('type' => 'string', 'max' => 140, 'is_null' => true),
            'jefper' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'cedpro' => array('type' => 'string', 'max' => 13, 'is_null' => true),
            'nompro' => array('type' => 'string', 'max' => 40, 'is_null' => true),
            'direccion' => array('type' => 'string', 'max' => 120, 'is_null' => true),
            'codciu' => array('type' => 'string', 'max' => 5, 'is_null' => true),
            'telefono' => array('type' => 'string', 'max' => 20, 'is_null' => true),
            'fax' => array('type' => 'string', 'max' => 13, 'is_null' => true),
            'email' => array('type' => 'email', 'max' => 100, 'is_null' => true),
            'codzon' => array('type' => 'string', 'max' => 9),
            'dirpri' => array('type' => 'string', 'max' => 120, 'is_null' => true),
            'telpri' => array('type' => 'string', 'max' => 20, 'is_null' => true),
            'ciupri' => array('type' => 'string', 'max' => 5, 'is_null' => true),
            'ofiafi' => array('type' => 'string', 'max' => 2),
            'codase' => array('type' => 'string', 'max' => 2),
            'calemp' => array('type' => 'string', 'max' => 1),
            'tipemp' => array('type' => 'string', 'max' => 1),
            'tipsoc' => array('type' => 'string', 'max' => 2),
            'tipapo' => array('type' => 'string', 'max' => 1),
            'forpre' => array('type' => 'string', 'max' => 1),
            'pymes' => array('type' => 'string', 'max' => 1),
            'contratista' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'colegio' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'todmes' => array('type' => 'string', 'max' => 1),
            'matmer' => array('type' => 'string', 'max' => 12, 'is_null' => true),
            'codact' => array('type' => 'string', 'max' => 6),
            'codind' => array('type' => 'string', 'max' => 2),
            'feccer' => array('type' => 'date', 'is_null' => false),
            'actapr' => array('type' => 'string', 'max' => 50),
            'fecapr' => array('type' => 'date'),
            'fecafi' => array('type' => 'date'),
            'fecsis' => array('type' => 'date'),
            'estado' => array('type' => 'string', 'max' => 1),
            'resest' => array('type' => 'string', 'max' => 15, 'is_null' => true),
            'codest' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'fecest' => array('type' => 'date', 'is_null' => true),
            'tottra' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'totapo' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'totcon' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'tothij' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'tother' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'totpad' => array('type' => 'rangelength', 'min' => 1, 'max' => 11),
            'fecmer' => array('type' => 'date', 'is_null' => true),
            'tipdur' => array('type' => 'string', 'max' => 1),
            'feccor' => array('type' => 'date', 'is_null' => true),
            'feccam' => array('type' => 'date', 'is_null' => true),
            'valmor' => array('type' => 'string', 'max' => 50, 'is_null' => true),
            'permor' => array('type' => 'string', 'max' => 150, 'is_null' => true),
            'fosfec' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'telt' => array('type' => 'string', 'max' => 20, 'is_null' => true),
            'telr' => array('type' => 'string', 'max' => 20, 'is_null' => true),
            'mailr' => array('type' => 'email', 'max' => 100, 'is_null' => true),
            'mailt' => array('type' => 'email', 'max' => 100, 'is_null' => true),
            'giass' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'actugp' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'correo' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'nota' => array('type' => 'string', 'max' => 255, 'is_null' => true),
            'coddocrepleg' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'priaperepleg' => array('type' => 'string', 'max' => 25, 'is_null' => true),
            'segaperepleg' => array('type' => 'string', 'max' => 25, 'is_null' => true),
            'prinomrepleg' => array('type' => 'string', 'max' => 25, 'is_null' => true),
            'segnomrepleg' => array('type' => 'string', 'max' => 25, 'is_null' => true),
            'codcaj' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'codsuc' => array('type' => 'string', 'max' => 3, 'is_null' => false),
            'codlis' => array('type' => 'string', 'max' => 3, 'is_null' => false),
            'cedtra' => array('type' => 'string', 'max' => 16, 'is_null' => false),
            'rural' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'agro' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'cabhog' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'captra' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'tipdis' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'horas' => array('type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => false),
            'salario' => array('type' => 'rangelength', 'min' => 1, 'max' => 8, 'is_null' => false),
            'tipsal' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'fecsal' => array('type' => 'date', 'is_null' => false),
            'sexo' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'estciv' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'tipcon' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'feccon' => array('type' => 'date', 'is_null' => true),
            'trasin' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'vivienda' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'nivedu' => array('type' => 'string', 'max' => 2, 'is_null' => false),
            'tipcot' => array('type' => 'string', 'max' => 2, 'is_null' => false),
            'vendedor' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'empleador' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'tippag' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'codcue' => array('type' => 'string', 'max' => 3, 'is_null' => true),
            'ofides' => array('type' => 'string', 'max' => 4, 'is_null' => true),
            'codgru' => array('type' => 'string', 'max' => 3, 'is_null' => true),
            'codban' => array('type' => 'string', 'max' => 5, 'is_null' => true),
            'numcue' => array('type' => 'string', 'max' => 17, 'is_null' => true),
            'tipcue' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'feccar' => array('type' => 'date', 'is_null' => true),
            'codcat' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'fecnac' => array('type' => 'date'),
            'ciunac' => array('type' => 'string', 'max' => 5, 'is_null' => true),
            'fecpre' => array('type' => 'date', 'is_null' => false),
            'giro' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'giro2' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'codgir' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'codgir2' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'carnet' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'benef' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'ruaf' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'ruasub' => array('type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => true),
            'nota' => array('type' => 'string', 'max' => 50, 'is_null' => true),
            'numtar' => array('type' => 'string', 'max' => 50, 'is_null' => true),
            'fecrua' => array('type' => 'date', 'is_null' => true),
            'fosfec' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'fecact' => array('type' => 'date', 'is_null' => true),
            'tipjor' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'usuario' => array('type' => 'string', 'max' => 10, 'is_null' => true),
            'correo' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'tottra' => array('type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => true),
            'cargo' => array('type' => 'string', 'max' => 100, 'is_null' => true),
            'orisex' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'dirlab' => array('type' => 'string', 'max' => 150, 'is_null' => true),
            'ruralt' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'ciulab' => array('type' => 'string', 'max' => 10, 'is_null' => true),
            'pais' => array('type' => 'string', 'max' => 10, 'is_null' => true),
            'facvul' => array('type' => 'string', 'max' => 10, 'is_null' => true),
            'peretn' => array('type' => 'string', 'max' => 10, 'is_null' => true),
            'fecha_giro' => array('type' => 'string', 'max' => 10, 'is_null' => true),
            'resguardo_id' => array('type' => 'rangelength', 'min' => 1, 'max' => 5, 'is_null' => true),
            'pub_indigena_id' => array('type' => 'rangelength', 'min' => 1, 'max' => 3, 'is_null' => true),
            'traapo' => array('type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => true),
            'valapo' => array('type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => true),
            'tietra' => array('type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => true),
            'tratot' => array('type' => 'rangelength', 'min' => 1, 'max' => 11, 'is_null' => true),
        );
    }
}
