<?php

namespace App\Services\Entities;

use App\Services\Validator\ValidatorTrait;

class TrabajadorEntity
{
    use ValidatorTrait;

    protected $fillable = [
        'nit',
        'codsuc',
        'codlis',
        'cedtra',
        'coddoc',
        'priape',
        'segape',
        'prinom',
        'segnom',
        'direccion',
        'codciu',
        'telefono',
        'email',
        'codzon',
        'rural',
        'agro',
        'cabhog',
        'captra',
        'tipdis',
        'horas',
        'salario',
        'tipsal',
        'fecsal',
        'sexo',
        'estciv',
        'tipcon',
        'feccon',
        'trasin',
        'vivienda',
        'nivedu',
        'tipcot',
        'vendedor',
        'empleador',
        'tippag',
        'codcue',
        'ofides',
        'codgru',
        'codban',
        'numcue',
        'tipcue',
        'feccar',
        'codcat',
        'fecnac',
        'ciunac',
        'fecpre',
        'fecafi',
        'fecsis',
        'giro',
        'giro2',
        'codgir',
        'codgir2',
        'estado',
        'codest',
        'fecest',
        'carnet',
        'benef',
        'ruaf',
        'ruasub',
        'totcon',
        'tothij',
        'tother',
        'totpad',
        'nota',
        'numtar',
        'fecrua',
        'fosfec',
        'fecact',
        'tipjor',
        'usuario',
        'correo',
        'tottra',
        'cargo',
        'orisex',
        'dirlab',
        'ruralt',
        'ciulab',
        'pais',
        'facvul',
        'peretn',
        'fecha_giro',
        'resguardo_id',
        'pub_indigena_id',
        'fecret',
    ];

    protected function getRules()
    {
        return [
            'nit' => ['type' => 'string', 'max' => 14, 'is_null' => false],
            'codsuc' => ['type' => 'string', 'max' => 3, 'is_null' => false],
            'codlis' => ['type' => 'string', 'max' => 3, 'is_null' => false],
            'cedtra' => ['type' => 'string', 'max' => 16, 'is_null' => false],
            'coddoc' => ['type' => 'string', 'max' => 2, 'is_null' => false],
            'priape' => ['type' => 'string', 'max' => 20, 'is_null' => false],
            'segape' => ['type' => 'string', 'max' => 20, 'is_null' => true],
            'prinom' => ['type' => 'string', 'max' => 30, 'is_null' => false],
            'segnom' => ['type' => 'string', 'max' => 20, 'is_null' => true],
            'direccion' => ['type' => 'string', 'max' => 120, 'is_null' => true],
            'codciu' => ['type' => 'string', 'max' => 9, 'is_null' => false],
            'telefono' => ['type' => 'string', 'max' => 20, 'is_null' => true],
            'email' => ['type' => 'string', 'max' => 100, 'is_null' => true],
            'codzon' => ['type' => 'string', 'max' => 9, 'is_null' => false],
            'rural' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'agro' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'cabhog' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'captra' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'tipdis' => ['type' => 'string', 'max' => 2, 'is_null' => true],
            'horas' => ['type' => 'numeric', 'is_null' => false],
            'salario' => ['type' => 'rangelength', 'min' => 1, 'max' => 8, 'is_null' => false],
            'tipsal' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'fecsal' => ['type' => 'date', 'is_null' => false],
            'sexo' => ['type' => 'string', 'max' => 2, 'is_null' => true],
            'estciv' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'tipcon' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'feccon' => ['type' => 'date', 'is_null' => true],
            'trasin' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'vivienda' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'nivedu' => ['type' => 'string', 'max' => 2, 'is_null' => false],
            'tipcot' => ['type' => 'string', 'max' => 2, 'is_null' => false],
            'vendedor' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'empleador' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'tippag' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'codcue' => ['type' => 'string', 'max' => 3, 'is_null' => true],
            'ofides' => ['type' => 'string', 'max' => 4, 'is_null' => true],
            'codgru' => ['type' => 'string', 'max' => 3, 'is_null' => true],
            'codban' => ['type' => 'string', 'max' => 5, 'is_null' => true],
            'numcue' => ['type' => 'string', 'max' => 17, 'is_null' => true],
            'tipcue' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'feccar' => ['type' => 'date', 'is_null' => true],
            'codcat' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'fecnac' => ['type' => 'date', 'is_null' => false],
            'ciunac' => ['type' => 'string', 'max' => 5, 'is_null' => true],
            'fecpre' => ['type' => 'date', 'is_null' => false],
            'fecafi' => ['type' => 'date', 'is_null' => false],
            'fecsis' => ['type' => 'date', 'is_null' => false],
            'giro' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'giro2' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'codgir' => ['type' => 'string', 'max' => 2, 'is_null' => true],
            'codgir2' => ['type' => 'string', 'max' => 2, 'is_null' => true],
            'estado' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'codest' => ['type' => 'string', 'max' => 2, 'is_null' => true],
            'fecest' => ['type' => 'date', 'is_null' => true],
            'carnet' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'benef' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'ruaf' => ['type' => 'string', 'max' => 1, 'is_null' => false],
            'ruasub' => ['type' => 'numeric', 'is_null' => true],
            'totcon' => ['type' => 'numeric', 'is_null' => false],
            'tothij' => ['type' => 'numeric', 'is_null' => false],
            'tother' => ['type' => 'numeric', 'is_null' => false],
            'totpad' => ['type' => 'numeric', 'is_null' => false],
            'nota' => ['type' => 'string', 'max' => 50, 'is_null' => true],
            'numtar' => ['type' => 'string', 'max' => 50, 'is_null' => true],
            'fecrua' => ['type' => 'date', 'is_null' => true],
            'fosfec' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'fecact' => ['type' => 'date', 'is_null' => true],
            'tipjor' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'usuario' => ['type' => 'string', 'max' => 10, 'is_null' => true],
            'correo' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'tottra' => ['type' => 'numeric', 'is_null' => true],
            'cargo' => ['type' => 'string', 'max' => 100, 'is_null' => true],
            'orisex' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'dirlab' => ['type' => 'string', 'max' => 150, 'is_null' => true],
            'ruralt' => ['type' => 'string', 'max' => 1, 'is_null' => true],
            'ciulab' => ['type' => 'string', 'max' => 10, 'is_null' => true],
            'pais' => ['type' => 'string', 'max' => 10, 'is_null' => true],
            'facvul' => ['type' => 'string', 'max' => 10, 'is_null' => true],
            'peretn' => ['type' => 'string', 'max' => 10, 'is_null' => true],
            'fecha_giro' => ['type' => 'string', 'required' => true, 'max' => 10, 'is_null' => true],
            'resguardo_id' => ['type' => 'numeric', 'required' => true, 'is_null' => true],
            'pub_indigena_id' => ['type' => 'numeric', 'required' => true, 'is_null' => true],
            'fecret' => ['type' => 'date', 'is_null' => true],
        ];
    }
}
