<?php

namespace App\Services\Entities;

use App\Services\Validator\ValidatorTrait;

class TrabajadorEntity
{
    use ValidatorTrait;

    protected $fillable = array(
        'nit',
        'codsuc',
        'codlis',
        'cedtra',
        'coddoc',
        'priape',
        'segape',
        'prinom',
        'segnom',
        'direccion',
        'codciu',
        'telefono',
        'email',
        'codzon',
        'rural',
        'agro',
        'cabhog',
        'captra',
        'tipdis',
        'horas',
        'salario',
        'tipsal',
        'fecsal',
        'sexo',
        'estciv',
        'tipcon',
        'feccon',
        'trasin',
        'vivienda',
        'nivedu',
        'tipcot',
        'vendedor',
        'empleador',
        'tippag',
        'codcue',
        'ofides',
        'codgru',
        'codban',
        'numcue',
        'tipcue',
        'feccar',
        'codcat',
        'fecnac',
        'ciunac',
        'fecpre',
        'fecafi',
        'fecsis',
        'giro',
        'giro2',
        'codgir',
        'codgir2',
        'estado',
        'codest',
        'fecest',
        'carnet',
        'benef',
        'ruaf',
        'ruasub',
        'totcon',
        'tothij',
        'tother',
        'totpad',
        'nota',
        'numtar',
        'fecrua',
        'fosfec',
        'fecact',
        'tipjor',
        'usuario',
        'correo',
        'tottra',
        'cargo',
        'orisex',
        'dirlab',
        'ruralt',
        'ciulab',
        'pais',
        'facvul',
        'peretn',
        'fecha_giro',
        'resguardo_id',
        'pub_indigena_id',
        'fecret'
    );

    protected function getRules()
    {
        return array(
            'nit' => array('type' => 'string', 'max' => 14, 'is_null' => false),
            'codsuc' => array('type' => 'string', 'max' => 3, 'is_null' => false),
            'codlis' => array('type' => 'string', 'max' => 3, 'is_null' => false),
            'cedtra' => array('type' => 'string', 'max' => 16, 'is_null' => false),
            'coddoc' => array('type' => 'string', 'max' => 2, 'is_null' => false),
            'priape' => array('type' => 'string', 'max' => 20, 'is_null' => false),
            'segape' => array('type' => 'string', 'max' => 20, 'is_null' => true),
            'prinom' => array('type' => 'string', 'max' => 30, 'is_null' => false),
            'segnom' => array('type' => 'string', 'max' => 20, 'is_null' => true),
            'direccion' => array('type' => 'string', 'max' => 120, 'is_null' => true),
            'codciu' => array('type' => 'string', 'max' => 9, 'is_null' => false),
            'telefono' => array('type' => 'string', 'max' => 20, 'is_null' => true),
            'email' => array('type' => 'string', 'max' => 100, 'is_null' => true),
            'codzon' => array('type' => 'string', 'max' => 9, 'is_null' => false),
            'rural' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'agro' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'cabhog' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'captra' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'tipdis' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'horas' => array('type' => 'numeric', 'is_null' => false),
            'salario' => array('type' => 'rangelength', 'min' => 1, 'max' => 8, 'is_null' => false),
            'tipsal' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'fecsal' => array('type' => 'date', 'is_null' => false),
            'sexo' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'estciv' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'tipcon' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'feccon' => array('type' => 'date', 'is_null' => true),
            'trasin' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'vivienda' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'nivedu' => array('type' => 'string', 'max' => 2, 'is_null' => false),
            'tipcot' => array('type' => 'string', 'max' => 2, 'is_null' => false),
            'vendedor' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'empleador' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'tippag' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'codcue' => array('type' => 'string', 'max' => 3, 'is_null' => true),
            'ofides' => array('type' => 'string', 'max' => 4, 'is_null' => true),
            'codgru' => array('type' => 'string', 'max' => 3, 'is_null' => true),
            'codban' => array('type' => 'string', 'max' => 5, 'is_null' => true),
            'numcue' => array('type' => 'string', 'max' => 17, 'is_null' => true),
            'tipcue' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'feccar' => array('type' => 'date', 'is_null' => true),
            'codcat' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'fecnac' => array('type' => 'date', 'is_null' => false),
            'ciunac' => array('type' => 'string', 'max' => 5, 'is_null' => true),
            'fecpre' => array('type' => 'date', 'is_null' => false),
            'fecafi' => array('type' => 'date', 'is_null' => false),
            'fecsis' => array('type' => 'date', 'is_null' => false),
            'giro' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'giro2' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'codgir' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'codgir2' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'estado' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'codest' => array('type' => 'string', 'max' => 2, 'is_null' => true),
            'fecest' => array('type' => 'date', 'is_null' => true),
            'carnet' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'benef' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'ruaf' => array('type' => 'string', 'max' => 1, 'is_null' => false),
            'ruasub' => array('type' => 'numeric', 'is_null' => true),
            'totcon' => array('type' => 'numeric', 'is_null' => false),
            'tothij' => array('type' => 'numeric', 'is_null' => false),
            'tother' => array('type' => 'numeric', 'is_null' => false),
            'totpad' => array('type' => 'numeric', 'is_null' => false),
            'nota' => array('type' => 'string', 'max' => 50, 'is_null' => true),
            'numtar' => array('type' => 'string', 'max' => 50, 'is_null' => true),
            'fecrua' => array('type' => 'date', 'is_null' => true),
            'fosfec' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'fecact' => array('type' => 'date', 'is_null' => true),
            'tipjor' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'usuario' => array('type' => 'string', 'max' => 10, 'is_null' => true),
            'correo' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'tottra' => array('type' => 'numeric', 'is_null' => true),
            'cargo' => array('type' => 'string', 'max' => 100, 'is_null' => true),
            'orisex' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'dirlab' => array('type' => 'string', 'max' => 150, 'is_null' => true),
            'ruralt' => array('type' => 'string', 'max' => 1, 'is_null' => true),
            'ciulab' => array('type' => 'string', 'max' => 10, 'is_null' => true),
            'pais' => array('type' => 'string', 'max' => 10, 'is_null' => true),
            'facvul' => array('type' => 'string', 'max' => 10, 'is_null' => true),
            'peretn' => array('type' => 'string', 'max' => 10, 'is_null' => true),
            'fecha_giro' => array('type' => 'string', 'required' => true, 'max' => 10, 'is_null' => true),
            'resguardo_id' => array('type' => 'numeric', 'required' => true, 'is_null' => true),
            'pub_indigena_id' => array('type' => 'numeric', 'required' => true, 'is_null' => true),
            'fecret' => array('type' => 'date', 'is_null' => true)
        );
    }
}
